sudo: required
services:
- docker
language: bash
env:
  global:
    - LANG=de_DE.UTF-8
script:
- pwd
- docker-compose version
- >
  if [ "$TRAVIS_BRANCH" !== "ubuntu64" ] && [ "$TRAVIS_BRANCH" !== "rpi" ]; then
    # exit
    exit 0;
  fi

# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset;
# build image
- cd ./build
- docker-compose build
# push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push karsten13/alexa:$TRAVIS_BRANCH
# test image
- cd ../run
- echo "ProductID=XX" > .env
- echo "ClientID=XX" >> .env
- echo "ClientSecret=XX" >> .env
- echo "DeviceSerialNumber=XX" >> .env
- echo "KeyStorePassword=XX" >> .env
- cat ../container/javaclient/config.json

- docker-compose up -d
