version: '3'

services:
  alexa:
    container_name: al
    image: karsten13/alexa:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/alexa/container:/srv/alexa-avs-sample-app/samples
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc:/opt/vc/:ro
      - /run/systemd:/run/systemd
    network_mode: host
    environment:
      # system params:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - DISPLAY=unix$DISPLAY
      # amazon params:
      - ProductID=${ProductID}
      - ClientID=${ClientID}
      - ClientSecret=${ClientSecret}
      - DeviceSerialNumber=${DeviceSerialNumber}
      - KeyStorePassword=${KeyStorePassword}
      # certificate params:
      - Country=DE
      - State=HESSEN
      - City=FRANKFURT
      - Organization=karsten13
      - Locale=de-DE
      # audio params
      - Audio=3.5mm
      - Wake_Word_Detection_Enabled=true
      - Wake_Word_Detection=kitt_ai
    devices:
      - /dev/vchiq
      - /dev/snd
      - /dev/bus/usb
    entrypoint: 
      - /srv/alexa-avs-sample-app/entrypoint.sh
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true      
    restart: always
