version: '3'

services:
  alexa:
    container_name: al
    image: karsten13/alexa:latest
    volumes:
      - ~/alexa/container/companionService/config.js:/srv/alexa-avs-sample-app/samples/companionService/config.js
      - ~/alexa/container/companionService/refresh_tokens:/srv/alexa-avs-sample-app/samples/companionService/refresh_tokens
      - ~/alexa/container/javaclient/config.json:/srv/alexa-avs-sample-app/samples/javaclient/config.json
      - ~/alexa/container/javaclient/certs:/srv/alexa-avs-sample-app/samples/javaclient/certs
#      - ~/alexa/container/wakeWordAgent/Hilde.pmdl:/srv/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources/alexa.umdl
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
    environment:
      # system params:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - DISPLAY=unix$DISPLAY
      # amazon params:
      - ProductID=${ProductID}
      - ClientID=${ClientID}
      - ClientSecret=${ClientSecret}
      - DeviceSerialNumber=${DeviceSerialNumber}
      - KeyStorePassword=${KeyStorePassword}
      # certificate params:
      - Country=DE
      - State=HESSEN
      - City=FRANKFURT
      - Organization=karsten13
      - Locale=de-DE
      # audio params
      - Audio=3.5mm
      - Wake_Word_Detection_Enabled=true
      - Wake_Word_Detection=kitt_ai
    devices:
      - /dev/vchiq
      - /dev/snd
      - /dev/bus/usb
    entrypoint: 
      - /srv/alexa-avs-sample-app/entrypoint.sh
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true      
    restart: always
