version: '3'

services:
  alexa:
    container_name: al
    image: karsten13/alexa:latest
    ports:
      - 3000:3000
    volumes:
      - ~/alexa/container/companionService:/srv/alexa-avs-sample-app/samples/companionService
      - ~/alexa/container/javaclient/config.json:/srv/alexa-avs-sample-app/samples/javaclient/config.json
      - ~/alexa/container/javaclient/certs:/srv/alexa-avs-sample-app/samples/javaclient/certs
#      - ~/alexa/container/wakeWordAgent/Hilde.pmdl:/srv/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources/alexa.umdl
      - /tmp/.X11-unix:/tmp/.X11-unix
#      - /opt/vc:/opt/vc/:ro
    environment:
      # system params:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - DISPLAY
      # amazon params:
      - ProductID=${ProductID}
      - ClientID=${ClientID}
      - ClientSecret=${ClientSecret}
      - DeviceSerialNumber=${DeviceSerialNumber}
      - KeyStorePassword=${KeyStorePassword}
      # certificate params:
      - Country=DE
      - State=HESSEN
      - City=FRANKFURT
      - Organization=karsten13
      - Locale=de-DE
      # audio params
      - Audio=HDMI
      - Wake_Word_Detection_Enabled=false
      - Wake_Word_Detection=kitt_ai
    devices:
#      - /dev/vchiq
      - /dev/snd
      - /dev/bus/usb
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/dri/card0:/dev/dri/card0
    entrypoint: 
      - /srv/alexa-avs-sample-app/entrypoint.sh
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true      
    restart: always
